### DISCUSSION TITLE
Coverage Report using `pytest-cov`

### DISCUSSION THREAD

**Discussion by billsioros** [Neoteroi/BlackSheep#513] [Q&A] [answered]
Hello 👋🏽 everyone,

I'm trying to create a coverage report for my application and I noticed that my controllers report a 0% coverage even though I use the `TestClient` to perform requests. My configuration (`pyproject.toml`) is as follows:

```toml
[tool.pytest.ini_options]
pythonpath = [ "src" ]
asyncio_default_fixture_loop_scope = "session"
addopts = "-vv --color=yes --cov=api --cov-report=term-missing --cov-report=html"
log_cli = false
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_level = "INFO"
python_files = "test_*.py"
python_functions = "test_*"
testpaths = "tests"
markers = [
  "unit: Unit tests",
  "integration: Integration tests",
  "skip: Skip tests",
  "xfail: Expected to fail tests",
  "asyncio: Mark test to be run with pytest-asyncio",
]

[tool.coverage.paths]
source = [ "src" ]

[tool.coverage.run]
branch = true
source = [ "api" ]
concurrency = [ "greenlet", "thread" ]

[tool.coverage.report]
```

Could you please assist me?

Thanks! 😋

**Comment by sinisaos** [comment, marked as answer]
@billsioros I'm tried to test a simple `Hello World` application. Here is the project `tree`.
```bash
.
├── htmlcov
├── __pycache__
├── pyproject.toml
├── src
│   ├── __init__.py
│   └── server.py
└── tests
    ├── conftest.py
    ├── __init__.py
    └── test_app.py
```
I modified your `pyproject.toml` like this 
```toml
[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_default_fixture_loop_scope = "session"
log_cli = false
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_level = "INFO"
python_files = "test_*.py"
python_functions = "test_*"
testpaths = "tests"
markers = [
  "unit: Unit tests",
  "integration: Integration tests",
  "skip: Skip tests",
  "xfail: Expected to fail tests",
  "asyncio: Mark test to be run with pytest-asyncio",
]

[tool.coverage.report]
fail_under = 90

[tool.coverage.run]
branch = true
source = ["src"]
disable_warnings = ['no-data-collected']
command_line = "-m pytest -vv --color=yes --cov=src --cov-report=term-missing --cov-report=html"
```

You need to `coverage run` from the `src` directory and everything works (tests and coverage). 
Hope this helps.
